project_id = "hseggnvxoiujekyhtuqx"

[functions.parse-brand-guidelines]
verify_jwt = false

[functions.generate-content-image]
verify_jwt = false

[functions.generate-post-content]
verify_jwt = false
